### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Adityashah007** [artemkaxboy/red-exporter#28]
Is there any video related to this

**Comment by artemkaxboy** [comment]
I'm afraid there is no any videos. What kind of video you'd like to see?

**Comment by Adityashah007** [comment]
Full walkthrough Of Implementation

**Comment by artemkaxboy** [comment]
It's not going to appear in the nearest feature. The application now is aimed at those who are already familiar with Prometheus and Grafana.
What I can now, is clarify specific questions about the deploy and setup and add them into README, but I cannot make full step-by-step video.

**Comment by Adityashah007** [comment]
ok, please mention all the steps in the Readme file

**Comment by Adityashah007** [comment]
Do we have to deploy this on the docker
If iam using redmine on localhost:8080
which port should  this code be running
and what will be the host name db name if using sql

**Comment by artemkaxboy** [comment]
-Do we have to deploy this on the docker
-Yes

-If iam using redmine on localhost:8080, which port should this code be running
-It doesn't matter any port you want, e.g. 8081, to use another port you have to change the left part of parameter `--port` in run command

-what will be the host name db name if using sql
-It depends on DB settings, the easiest way is to copy connection settings from your Redmine instance settings

**Comment by Adityashah007** [comment]
for example, if   I am using this docker-compose

version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine


where should I use your docker-compose

services:
  redmine-exporter:
    image: artemkaxboy/red-exporter
    environment:
      DATABASE_HOST: ${DATABASE_HOST:?}
      DATABASE_NAME: ${DATABASE_NAME:?}
      DATABASE_USERNAME: ${DATABASE_USERNAME:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      REDMINE_PROJECTS: ${REDMINE_PROJECTS:-}
      REDMINE_USERS: ${REDMINE_USERS:-}
    deploy:
      restart_policy:
        delay: 600s
    ports:
      - "8080:8080"


and while we create a Docker image  Redmine is at default settings and does not contain any project and there is only one user admin 


please guide me with all the fields that I have to fill in your Docker compose and what should be the change in Ports

**Comment by artemkaxboy** [comment]
Must be something like this:
```yml
version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    ports:
    - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine

  redmine-exporter:
    image: artemkaxboy/red-exporter
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: redmine
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
      REDMINE_USERS: 1
    ports:
    - "8081:8080"
```

It will run `redmine-exporter` in one bridge network with the other containers, so you can use `db` service name as the `DATABASE_HOST`. And pay attention that `ports` section maps host port `8081` to port `8080` of the container.

But while you have no projects there is no metrics which exporter could collect. Could you please tell what you want to achieve by running this all? Which metrics are you planning to collect?
